/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app.route'
import { Route as moduleSessionSessionDotrouteRouteImport } from './module/session/session.route'
import { Route as moduleAuthAuthDotrouteRouteImport } from './module/auth/auth.route'
import { Route as moduleHomeHomeDotrouteRouteImport } from './module/home/home.route'
import { Route as moduleSessionSessionDetailDotrouteRouteImport } from './module/session/session-detail.route'

const moduleSessionSessionDotrouteRoute =
  moduleSessionSessionDotrouteRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const moduleAuthAuthDotrouteRoute = moduleAuthAuthDotrouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const moduleHomeHomeDotrouteRoute = moduleHomeHomeDotrouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const moduleSessionSessionDetailDotrouteRoute =
  moduleSessionSessionDetailDotrouteRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof moduleHomeHomeDotrouteRoute
  '/login': typeof moduleAuthAuthDotrouteRoute
  '/sessions': typeof moduleSessionSessionDotrouteRoute
  '/sessions/$sessionId': typeof moduleSessionSessionDetailDotrouteRoute
}
export interface FileRoutesByTo {
  '/': typeof moduleHomeHomeDotrouteRoute
  '/login': typeof moduleAuthAuthDotrouteRoute
  '/sessions': typeof moduleSessionSessionDotrouteRoute
  '/sessions/$sessionId': typeof moduleSessionSessionDetailDotrouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof moduleHomeHomeDotrouteRoute
  '/login': typeof moduleAuthAuthDotrouteRoute
  '/sessions': typeof moduleSessionSessionDotrouteRoute
  '/sessions/$sessionId': typeof moduleSessionSessionDetailDotrouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/sessions' | '/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/sessions' | '/sessions/$sessionId'
  id: '__root__' | '/' | '/login' | '/sessions' | '/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  moduleHomeHomeDotrouteRoute: typeof moduleHomeHomeDotrouteRoute
  moduleAuthAuthDotrouteRoute: typeof moduleAuthAuthDotrouteRoute
  moduleSessionSessionDotrouteRoute: typeof moduleSessionSessionDotrouteRoute
  moduleSessionSessionDetailDotrouteRoute: typeof moduleSessionSessionDetailDotrouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof moduleSessionSessionDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof moduleAuthAuthDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof moduleHomeHomeDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof moduleSessionSessionDetailDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  moduleHomeHomeDotrouteRoute: moduleHomeHomeDotrouteRoute,
  moduleAuthAuthDotrouteRoute: moduleAuthAuthDotrouteRoute,
  moduleSessionSessionDotrouteRoute: moduleSessionSessionDotrouteRoute,
  moduleSessionSessionDetailDotrouteRoute:
    moduleSessionSessionDetailDotrouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
