/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app.route'
import { Route as moduleAuthAuthDotrouteRouteImport } from './module/auth/auth.route'
import { Route as moduleCompanyCompanyDotrouteRouteImport } from './module/company/company.route'
import { Route as moduleHomeHomeDotrouteRouteImport } from './module/home/home.route'
import { Route as moduleCompanyCompanyDetailDotrouteRouteImport } from './module/company/company-detail.route'

const moduleAuthAuthDotrouteRoute = moduleAuthAuthDotrouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const moduleCompanyCompanyDotrouteRoute =
  moduleCompanyCompanyDotrouteRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => rootRouteImport,
  } as any)
const moduleHomeHomeDotrouteRoute = moduleHomeHomeDotrouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const moduleCompanyCompanyDetailDotrouteRoute =
  moduleCompanyCompanyDetailDotrouteRouteImport.update({
    id: '/company/$companyId',
    path: '/company/$companyId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof moduleHomeHomeDotrouteRoute
  '/company': typeof moduleCompanyCompanyDotrouteRoute
  '/login': typeof moduleAuthAuthDotrouteRoute
  '/company/$companyId': typeof moduleCompanyCompanyDetailDotrouteRoute
}
export interface FileRoutesByTo {
  '/': typeof moduleHomeHomeDotrouteRoute
  '/company': typeof moduleCompanyCompanyDotrouteRoute
  '/login': typeof moduleAuthAuthDotrouteRoute
  '/company/$companyId': typeof moduleCompanyCompanyDetailDotrouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof moduleHomeHomeDotrouteRoute
  '/company': typeof moduleCompanyCompanyDotrouteRoute
  '/login': typeof moduleAuthAuthDotrouteRoute
  '/company/$companyId': typeof moduleCompanyCompanyDetailDotrouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/company' | '/login' | '/company/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/company' | '/login' | '/company/$companyId'
  id: '__root__' | '/' | '/company' | '/login' | '/company/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  moduleHomeHomeDotrouteRoute: typeof moduleHomeHomeDotrouteRoute
  moduleCompanyCompanyDotrouteRoute: typeof moduleCompanyCompanyDotrouteRoute
  moduleAuthAuthDotrouteRoute: typeof moduleAuthAuthDotrouteRoute
  moduleCompanyCompanyDetailDotrouteRoute: typeof moduleCompanyCompanyDetailDotrouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof moduleAuthAuthDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof moduleCompanyCompanyDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof moduleHomeHomeDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof moduleCompanyCompanyDetailDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  moduleHomeHomeDotrouteRoute: moduleHomeHomeDotrouteRoute,
  moduleCompanyCompanyDotrouteRoute: moduleCompanyCompanyDotrouteRoute,
  moduleAuthAuthDotrouteRoute: moduleAuthAuthDotrouteRoute,
  moduleCompanyCompanyDetailDotrouteRoute:
    moduleCompanyCompanyDetailDotrouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
